blacklisted_tracks:
  - 2mnXxnrX5vCGolNkaFvVeM
  - 5MxFWjuqQIsbNWbMdMdbli
  - 1WCEAGGRD066z2Q89ObXTq
  - 4WuOWVnAqvEQxgSRrspBgt
  - 2Ch7LmS7r2Gy2kc64wv3Bz
  - 26b3oVLrRUaaybJulow9kz
  - 0eJmsdfbAOM1KD0w50EhlD
  - 63WuQOXohQIxOxIFA2K7bR
