blacklisted_tracks:
  - 2mnXxnrX5vCGolNkaFvVeM
  - 5MxFWjuqQIsbNWbMdMdbli
  - 1WCEAGGRD066z2Q89ObXTq
  - 4WuOWVnAqvEQxgSRrspBgt
  - 2Ch7LmS7r2Gy2kc64wv3Bz
  - 26b3oVLrRUaaybJulow9kz
  - 7MiLmLbwNoyf47xQ4TCVYp
  - 3EMwCbvaeyWVZb3ae0roHt
  - 5Lno0hPhvo7BzXVLQzDIS3
  - 4w3tQBXhn5345eUXDGBWZG
  - 1GdtMDRiaF1EnG2LJpELme
  - 0TuD1UPKYa0Cz7dbd5590X
  - 7vidktgNZFQylTgH1GEnMs